language: node_js
node_js:
  - '0.12'

before_install:
  - npm install -g typescript bower tsd gulp
  - bower install
  - tsd reinstall --overwrite --save

script:
  - gulp build-dist

notifications:
  email:
    - jeevan@jeevanjames.com
